Esri/solutions-webappbuilder-widgets

BatchEditor/README.md, BombThreat/README.md, CI_KR_Chart/README.md, CostAnalysis/README.md, DirectionsWithBarriers/README.md, ERG/README.md, GeoLookup/README.md, ImageInfo/README.md, ImageMensuration/README.md, ImageProperties/README.md, ImageSelect/README.md, MissionEditor/README.md, NetworkTrace/README.md, README.md, ServiceFeasibility/README.md, WAMITimeSlider/README.md
=> removed tailcoat references

CI_KR_Chart/manifest.json
Updating Description in manifest.json for CI_KR_Chart
=> Updating Description in manifest.json

ElevationProfileTable/README.md
@conklinbd updated readme.md for elevation profile table widget
=> updated README.md

ElevationProfileTable/README.md
Added sections for LOS python script
=> README.md pull

ElevationProfileTable/ElevationProfile/css/style.css, ElevationProfileTable/ElevationProfile/widget.js, ElevationProfileTable/config.json, ElevationProfileTable/css/style.css, ElevationProfileTable/setting/Setting.js
@conklinbd FYI. push to address issues
=> Incremental push

ElevationProfileTable/ElevationProfile/widget.js
@conklinbd pull request to address issue of busy cursor during LOS operation
=> added busy cursor for LOS operation

README.md
This is a dead link; Cost analysis was moved to a branch.
=> Updating cost analysis widget link

BombThreat/Widget.js
=> Bomb Threat Widget fixes #171

BombThreat/Widget.html, BombThreat/Widget.js
=> Bomb Threat widget fixes #170 and #172

NetworkTrace/Widget.js, NetworkTrace/css/style.css, NetworkTrace/nls/strings.js, NetworkTrace/setting/Setting.js, NetworkTrace/setting/inputData.html, NetworkTrace/setting/inputSetting.html, NetworkTrace/setting/inputSetting.js, NetworkTrace/setting/nls/strings.js, NetworkTrace/setting/outputData.html, NetworkTrace/setting/outputSetting.html
#203- Network Trace - Settings GP parameters do not match the display name
#204- Network Trace - Settings - Default labels for output to Display Name specified in the service
#205- Network Trace - Settings - Default tooltip to description from service
#206- Network Trace - Settings - update tooltip for Unique ID field
=> V1.3 - Resolved issues related to labels, tooltips, updated tooltip for unique ID field and removed 'Add' suffix for inputs in widget

CostAnalysis/manifest.json
Missing comma in manifest.json
=> Bad json file

ServiceFeasibility/Widget.html, ServiceFeasibility/Widget.js, ServiceFeasibility/css/style.css, ServiceFeasibility/setting/Setting.html, ServiceFeasibility/setting/Setting.js, ServiceFeasibility/setting/css/style.css, ServiceFeasibility/setting/nls/strings.js
Resolved following issues:
#258 Service Feasibility - WebMap layer filters not honored by Access
point queries
#252 Service Feasibility - Slider jitters
#251 Service Feasibility - UI issues with Dart theme
Added following enhancements:
#228 Service Feasibility - Hide Access Device list and select closest
#227 Service Feasibility - Display a cost instead of route length
#226 Service Feasibility - Option to turn off Barriers
#225 Service Feasibility - Make Businesses optional
#224 Service Feasibility - Leverage Travel Modes
=> V1.4 Resolved bug fixes & enhancements

BatchAttributeEditor/Widget.js
=> trying to make filter work both ways

NetworkTrace/Widget.html, NetworkTrace/Widget.js, NetworkTrace/css/style.css, NetworkTrace/setting/Setting.html, NetworkTrace/setting/Setting.js, NetworkTrace/setting/css/style.css, NetworkTrace/setting/inputData.html, NetworkTrace/setting/inputSetting.js, NetworkTrace/setting/inputSymbolChooser.js, NetworkTrace/setting/nls/strings.js, NetworkTrace/setting/othersSetting.html, NetworkTrace/setting/othersSetting.js, NetworkTrace/setting/outageSetting.html, NetworkTrace/setting/outageSetting.js, NetworkTrace/setting/outputData.html, NetworkTrace/setting/outputSetting.js, NetworkTrace/setting/outputSymbolChooser.js, NetworkTrace/setting/summarySetting.html, NetworkTrace/setting/summarySetting.js, NetworkTrace/setting/symbolChooserTemplate.html
Resolved following issues:
#270 Network Trace - Cannot delete the last flag
#263 Network Trace - Feature is not highlighted on smartphones
#262 Network Trace - In tab theme UI is getting distorted
#261 Network Trace - Unable to change highlighter image
#260 Network Trace - In IE9 Dart theme UI is distorted
#236 Network Trace - Legibility with 1.2 Dart/Launchpad Themes
Added following enhancements:
#207 Network Trace - Summary Text enhancement
=> V1.6 Resolved bug fixes & enhancements

BatchAttributeEditor/Widget.js, BatchAttributeEditor/css/style.css, BatchAttributeEditor/nls/strings.js
bold the layer name to reflect a filter and catch for invalid field.
=> bold the layer name to reflect a filter and catch for invalid field.

ERG/FacilitiesPane.js, ERG/FacilitiesView.js, ERG/README.md, ERG/Widget.html, ERG/Widget.js, ERG/config.json, ERG/css/style.css, ERG/manifest.json
@conklinbd updated ERG widget to 1.2. enhanced UI and logic.
=> Updated to v.1.2

BombThreat/README.md
@conklinbd updated readme to reflect changes for v.1.2
=> Updated readme

BombThreat/Widget.js
=> Fixes #168

ServiceFeasibility/Widget.html, ServiceFeasibility/Widget.js, ServiceFeasibility/css/style.css
Resolved following tickets:
#293 Service Feasibility - Resizing businesses passed
#292 Service Feasibility - retain graphics on error
=> V1.7 Resolved bug fixes

CI_KR_Chart/README.md, CI_KR_Chart/config.json
config.json points to Naperville, IL Infrastructure service.  Readme was
modified for more clarity in the instructions section.
=> Updated config and README

ServiceFeasibility/Widget.js, ServiceFeasibility/setting/Setting.html, ServiceFeasibility/setting/Setting.js, ServiceFeasibility/setting/attribute-parameter.js, ServiceFeasibility/setting/nls/strings.js
Resolved following tickets:
#328 Service Feasibility - rounding to 2 decimal places
#327 Service Feasibility - missing tooltips
#273 Expose rounding option for result
=> V1.8 Service Feasibility - Resolved bug fixes & changes(Support)

README.md
@conklinbd removed broken link "Directions with Barriers"
=> Removed Directions with Barriers link

ERG/README.md, ERG/Widget.html, ERG/Widget.js, ERG/manifest.json, ERG/nls/strings.js
=> updated to v.1.3

FilterEditor/manifest.json
set property hasVersionManger to false
=> updated manifest.json

ERG/FacilitiesPane.js, ERG/FacilitiesView.js, ERG/README.md, ERG/Widget.js, ERG/config.json
Fixed logic on passing data to GP services (Chemical and Placard)
=> Fixes #363

FilterEditor/FilterEditor.js
Fixed issue with duplicate feature layer names in the layer drop down list
=> Fixed layer drop-down list issue

ERG/Widget.js, ERG/config.json
added support for cors in widget.js and config.json
=> Added cors support

CoordinateTool/ReadMe.md, README.md
Changed the read me for WAB to reflect the Coordinate Tool. Also updated
information about the Coordinate tool in the ReadME
=> Changed Readme

NetworkTrace/Widget.js, NetworkTrace/css/style.css, NetworkTrace/setting/css/style.css, NetworkTrace/setting/outageSetting.html, NetworkTrace/setting/outputData.html
Resolved following tickets:
#410 Network Trace - Hint text alignment
#411 Network Trace - Save to Layer dropdowns
=> V1.10 Network Trace - Resolved bug fixes (Support)

InfoSummary/nls/ar/strings.js, InfoSummary/nls/cs/strings.js, InfoSummary/nls/da/strings.js, InfoSummary/nls/de/strings.js, InfoSummary/nls/el/strings.js, InfoSummary/nls/es/strings.js, InfoSummary/nls/et/strings.js, InfoSummary/nls/fi/strings.js, InfoSummary/nls/fr/strings.js, InfoSummary/nls/he/strings.js, InfoSummary/nls/it/strings.js, InfoSummary/nls/ja/strings.js, InfoSummary/nls/ko/strings.js, InfoSummary/nls/lt/strings.js, InfoSummary/nls/lv/strings.js, InfoSummary/nls/nb/strings.js, InfoSummary/nls/nl/strings.js, InfoSummary/nls/pl/strings.js, InfoSummary/nls/pt-br/strings.js, InfoSummary/nls/pt-pt/strings.js, InfoSummary/nls/ro/strings.js, InfoSummary/nls/ru/strings.js, InfoSummary/nls/sv/strings.js, InfoSummary/nls/th/strings.js, InfoSummary/nls/tr/strings.js, InfoSummary/nls/vi/strings.js, InfoSummary/nls/zh-cn/strings.js, InfoSummary/nls/zh-hk/strings.js, InfoSummary/nls/zh-tw/strings.js, InfoSummary/version.txt
missed some of the nls updates
=> Info summary

MapFilter/Widget.js, MapFilter/nls/strings.js
showcase natural language working with is/not null and not like
remove check for empty value box as this can be used to check `null`
@previnWong
=> sample usage

MapFilter/nls/strings.js, MapFilter/setting/nls/strings.js
=> nls change

GroupFilter/setting/Setting.js
add check at top for no layers in map
#524
=> no layers check

NetworkTrace/Widget.js
https://github.com/Esri/solutions-webappbuilder-widgets/issues/462
=> resolved issue

ElevationProfileTable/README.md, FilterEditor/README.md, README.md
Updating documentation for widgets that are being moved to mature support.
=> Lw mature support statement

Viewshed/README.md
new readme file for viewshed widget
=> Added README

GridOverlay/README.md, README.md
updated main and grid overlay README files.
=> Updated READMEs

GRG/tests/README.md, GRG/tests/grg-unit-test.js, GRG/tests/intern-client.js, GRG/tests/intern.js
=> Created unit test

GRG/views/TabCreateAreaGRG.js, GRG/views/TabCreatePointGRG.js, GRG/views/drawGRG.js
Addressed issue of how portal/ago changes field names to lower case when creating a service in code
=> Changed field names to lower case

DistanceAndDirection/models/DirectionalLineSymbol.js, DistanceAndDirection/views/TabLine.js
Added logic of creating directional arrows to polyline.
=> Added arrows to line logic

DistanceAndDirection/models/DirectionalLineSymbol.js, DistanceAndDirection/views/TabCircle.js, DistanceAndDirection/views/TabLine.js
something weird happened with initial PR for this work. Doing another PR.
=> Persist inputs in dialog

DistanceAndDirection/templates/TabEllipse.html, DistanceAndDirection/views/TabEllipse.js
addresses issue #697 
@kgonzago, please review and merge
=> Fixed bug related to issue #697

DistanceAndDirection/Widget.js, DistanceAndDirection/models/EllipseFeedback.js, DistanceAndDirection/models/ShapeModel.js, DistanceAndDirection/views/TabEllipse.js
=> Addresses #699, #107 and #695

DistanceAndDirection/templates/TabLine.html
Removed line type option from the Line Tab.
=> Addresses #740

DistanceAndDirection/models/ShapeModel.js, DistanceAndDirection/views/TabCircle.js
=> Issue #737

DistanceAndDirection/models/LineFeedback.js, DistanceAndDirection/views/TabLine.js
End point is now formatted accordingly.
@csmoore Can you review and merge please?
=> Addresses #761

DistanceAndDirection/ReadMe.md, DistanceAndDirection/templates/TabLine.html
@csmoore can you review and merge? Thanks.
=> change geodesic to geodetic

CoordinateConversion/CoordinateControl.js, CoordinateConversion/util.js
Applied formatting logic for MGRS to accommodate for user specified custom format.
=> Fixes #808

CoordinateConversion/CoordinateControl.js, CoordinateConversion/util.js
Reverts Esri/solutions-webappbuilder-widgets#812
=> Revert "Fixes #808"

CoordinateConversion/ConfirmNotation.html, CoordinateConversion/ConfirmNotation.js, CoordinateConversion/CoordinateControl.js, CoordinateConversion/EditOutputCoordinate.html, CoordinateConversion/EditOutputCoordinate.js, CoordinateConversion/Widget.js, CoordinateConversion/config.json, CoordinateConversion/css/style.css, CoordinateConversion/dialogConfirm.js, CoordinateConversion/setting/Setting.html, CoordinateConversion/util.js
Added GEOREF, GARS, UTM (H)
Added Support for polar regions
Add the ability to add DD, DDM, DMS in long / lat order
Added confirm dialog for ambiguous coordinates
=> Ag coordinate conversion dev

Visibility/gpservices/Viewshed/Viewshed.py, Visibility/gpservices/Viewshed/tests/UnitTestUtilities.py, Visibility/gpservices/tests/Configuration.py, Visibility/gpservices/tests/README.md, Visibility/gpservices/tests/TestKickStart.bat, Visibility/gpservices/tests/TestRunner.py, Visibility/gpservices/tests/UnitTestUtilities.py, Visibility/gpservices/tests/VisibilityTestSuite.py, Visibility/gpservices/tests/VisibilityUtilitiesTestCase.py
Added unit test for python script Visibility widget
=> Visibility unit tests

Visibility/tests/visibility-base-unit-tests.js
added asserts for viewshed function
=> Added more unit tests

GRG/templates/TabCreateAreaGRG.html
Changed Cell Width to dijitNumberTextBox
=> Address issue #849

CoordinateConversion/CoordinateControl.js
When in polar regions the label for UTM & UTM(H) no longer change to UPS
and coordinates are left blank
=> Address issue #782

Visibility/Widget.js, Visibility/js/VisibilityControl.js, Visibility/manifest.json, Visibility/nls/strings.js, Visibility/setting/Setting.js, Visibility/setting/SettingDetail.js, Visibility/setting/nls/strings.js, Visibility/templates/VisibilityControl.html
Added checks for a valid GP Service in both the configuration settings and the widget itself.
Within the configuration settings the user will be shown:
and the widget configuration will not be saved.
If somebody tries to manually change the URL in the config file, then the widget will show the following for an unreachable URL:
and the following for a reachable but invalid URL:
=> Address Issue #872

DistanceAndDirection/Widget.html, DistanceAndDirection/Widget.js, DistanceAndDirection/css/style.css, DistanceAndDirection/models/CircleFeedback.js, DistanceAndDirection/models/EllipseFeedback.js, DistanceAndDirection/templates/TabCircle.html, DistanceAndDirection/templates/TabEllipse.html, DistanceAndDirection/templates/TabLine.html, DistanceAndDirection/templates/TabRange.html, DistanceAndDirection/views/TabCircle.js, DistanceAndDirection/views/TabEllipse.js, DistanceAndDirection/views/TabLine.js, DistanceAndDirection/views/TabRange.js
A large effort required for issue #898
=> Address issues #898 #899

CoordinateConversion/ReadMe.md, CoordinateConversion/THIS_IS_NO_LONGER_MAINTAINED.md
Changes to the repo to move to mature support and point our users
towards the widget that is now in core.
=> Moving Coordinate Conversion to Mature support

README.md
Removed reference to Coordinate Conversion and Grid Overlay
=> Removed reference to Cooridnate Conversion and Grid Overlay

ServiceFeasibility/Widget.js, ServiceFeasibility/manifest.json, ServiceFeasibility/setting/Setting.js, ServiceFeasibility/setting/attribute-parameter.js
Fix for checkbox issues arising from WAB 2.7.
=> Service feasibility 2 7 fix

NetworkTrace/setting/outageSetting.js, NetworkTrace/setting/outputSetting.js
Fix to Save to layer checkbox to setValue to True.
=> Fix to Save to layer checkbox to setValue to True.

ServiceFeasibility/setting/Setting.js
changed setValue to getValue typo to enable persisting layer save.
=> changed setValue to getValue typo to enable persisting layer save.

ServiceFeasibility/Widget.js
resolved check event on export dialog
=> resolved save issue with service feasibility
